config/routes.rb
JobBoard::Application.routes.draw do
  get  "/companies/login", to: "login#new"
  post "/companies/login", to: "login#create"
  get  "/companies/logout", to: "login#destroy"
  root to: "jobs#premium"

  resources :jobs do
    post "comments", to: "comments#create"
  end
  resources :companies, only:[:new, :create]
  delete "comments/:id", to: "comments#destroy", as: :comment

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :job, counter_cache: true
  validates_presence_of :body, :job_id, :name
end

app/models/company.rb
require "bcrypt"
class Company < ActiveRecord::Base
  has_many :jobs
  validates_presence_of :email, :name, :password
  validates_uniqueness_of :email
  validates_length_of :password, minimum: 6
  validates_confirmation_of :password

  def password=(new_password)
    @password = new_password
    self.encrypted_password = BCrypt::Password.create(@password)
  end

  def password
    @password
  end

  def valid_password?(password_to_validate)
    BCrypt::Password.new(encrypted_password) == password_to_validate
  end

end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :company
  has_many :comments
  scope :most_recent, order("created_at DESC")
  validates_presence_of :description, :title, :company_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :set_locale

  private

  def current_company
    @current_company ||= if session[:company_id]
                           Company.find_by_id(session[:company_id])
                         end
  end
  helper_method :current_company

  def set_locale
    locale = params[:locale] || cookies[:locale]

    if locale.present?
      I18n.locale = locale
      cookies[:locale] = { value: locale, expires: 30.days.from_now }
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @job = Job.find(params[:job_id])
    @comment = @job.comments.build(comment_params)

    if success = @comment.save
      CompanyMailer.new_comment(@job, @comment).deliver
    end

    respond_to do |format|
      format.html do
        if success
          flash[:notice] = "Comment was created with success!"
        else
          flash[:alert] = "Please fill in all fields to create a comment."
        end
        redirect_to @job
      end
      format.js
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to @comment.job, notice: "Comment destroyed with success."
  end

  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def comment_params
    params.require(:comment).permit(:name, :body, :job_id)
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)

    if @company.save
      redirect_to root_path, notice: "Company was successfully created."
    else
      render action: "new"
    end
  end

  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def company_params
    params.require(:company).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_filter :authorize_company, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.most_recent.includes(:company).all

    respond_to do |format|
      format.html
      format.json {render json: @jobs}
    end
  end

  def premium
    @jobs = Job.where(premium: true).most_recent.includes(:company).paginate(page: params[:page], per_page: 10)
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @job = Job.find(params[:id])
    @comments = @job.comments.order('id desc')

    respond_to do |format|
      format.html
      format.json{render json: @job}
    end
  end

  # GET /jobs/new
  def new
    @job = current_company.jobs.build
  end

  # GET /jobs/1/edit
  def edit
    @job = current_company.jobs.find(params[:id])
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = current_company.jobs.build(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render action: 'show', status: :created, location: @job }
      else
        format.html { render action: 'new' }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    @job = current_company.jobs.find(params[:id])
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job = current_company.jobs.find(params[:id])
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:title, :description, :premium, :company_id)
    end

    def authorize_company
      unless current_company
        redirect_to root_path, alert: "You need to login to continue"
      end
    end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def new

  end

  def create
    company = Company.find_by_email(params[:company][:email])

    if company && company.valid_password?(params[:company][:password])
      session[:company_id] = company.id
      redirect_to root_path
    else
      flash.now[:alert] = "Invalid e-mail or password"
      render action: "new"
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
  def job_title(job)
    title = raw("#{h(job.title)} - #{h(job.company.name)}")

    if job.premium
      title + content_tag(:strong, " (premium)")
    else
      title
    end
  end
end

app/views/comments/_comment.html.erb
<h4><%= t ".said", name: comment.name %>:</h4>
<%= simple_format comment.body %>
<%= t ".sent", timestamp: time_ago_in_words(comment.created_at) %>
<%= link_to t("links.destroy"), comment_path(comment), method: :delete, confirm: t("links.destroy_confirmation") %>

app/views/comments/_form.html.erb
<%= form_for [@job, Comment.new], html:{class: 'form-horizontal'}, remote: true do |f| %>
  <div class="control-group">
    <%= f.label :name, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :name %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :body, class: 'control-label' %>
    <div class="controls">
      <%= f.text_area :body, row: 5 %>
    </div>
  </div>
  <div class="control-group controls">
    <%= f.submit class: 'btn btn-primary' %><br />
  </div>
<% end %>

app/views/comments/create.js.erb
<% if @comment.errors.empty? %>
  $('#comments').append('<%=j render(@comment) %>');
  $('#new_comment')[0].reset();
  alert('Comment was created with success!');
<% else %>
  alert('Please fill in all fields to create a comment.');
<% end %>

app/views/companies/_form.html.erb
<%= form_for(@company, html: {class: 'form-horizontal'}) do |f| %>
    <% if @company.errors.any? %>
        <div id="alert error-alert">
          <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

          <ul>
            <% @company.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="control-group">
      <%= f.label :name, class: 'control-label' %>
      <div class="controls">
        <%= f.text_field :name %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :email, class: 'control-label' %>
      <div class="controls">
        <%= f.text_field :email %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :password, class: 'control-label' %>
      <div class="controls">
        <%= f.password_field :password %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :password_confirmation, class: 'control-label' %>
      <div class="controls">
        <%= f.password_field :password_confirmation %>
      </div>
    </div>
    <div class="control-group controls">
      <%= f.submit class: 'btn btn-primary' %>
    </div>
<% end %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/jobs/_form.html.erb
<%= form_for(@job, html: {class: 'form-horizontal'}) do |f| %>
  <% if @job.errors.any? %>
    <div id="alert error-alert">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
    <div class="control-group">
      <%= f.label :premium %><br>
      <%= f.check_box :premium %>
    </div>
  <div class="control-group">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="control-group controls">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/jobs/_job.html.erb
<h3><%= job_title job %></h3>

<%= simple_format job.description %>

<p>
  <%= pluralize(job.comments.size, "comment") %>
  <%= link_to 'Show', job %>
  <% if current_company == job.company %>
    <%= link_to 'Edit', edit_job_path(job) %>
    <%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
</p>

app/views/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<h1><%= t("jobs.index.listing") %></h1>

<%= render @jobs %>

<br>

<%= link_to 'New Job', new_job_path %>
<br />
<%= link_to 'Premium Jobs', root_path %>

app/views/jobs/new.html.erb
<h1>New job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/premium.html.erb
<h1>Premium jobs</h1>

<%= render @jobs %>
<%= will_paginate @jobs %>

<br>

<%= link_to 'New Job', new_job_path %>
<br />
<%= link_to 'All Jobs', jobs_path %>

app/views/jobs/show.html.erb
<h1><%= job_title @job %></h1>

<%= simple_format @job.description %>

<p>
  <%= pluralize(@job.comments.size, t("comments.count")) %> |
  <% if current_company == @job.company %>
    <%= link_to t("links.edit"), edit_job_path(@job) %> |
  <% end %>
  <%= link_to t("links.back"), jobs_path %>
</p>

<h2><%=  t ".new_comment" %></h2>
<%= render "comments/form" %>

<h2><%= t ".comments" %></h2>
<div id="comments">
    <%= render @job.comments %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>JobBoard</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="/" title="Job Board">Job Board</a>

      <ul class="nav">
        <li><%= link_to "English", locale: "en" %></li>
        <li><%= link_to "Português", locale: "pt-BR" %></li>
      </ul>

      <ul id="app-menu" class="nav pull-right">
        <li><%= link_to t("menu.premium_jobs"), root_path %></li>
        <li><%= link_to t("menu.all_jobs"), jobs_path %></li>
        <% if current_company %>
          <li><%= link_to t("menu.new_job"), new_job_path %></li>
          <li><a><%= t("menu.logged_as") %><%= current_company.name %></a></li>
          <li><%= link_to "Logout", companies_logout_path %></li>
        <% else %>
          <li><%= link_to t("menu.new_company"), new_company_path %></li>
          <li><%= link_to t("menu.login"), companies_login_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<div class="container">
  <% if notice %><p class="alert alert-success"><%= notice %></p><% end %>
  <% if alert %><p class="alert alert-error"><%= alert %></p><% end %>
  <%= yield %>
</div>

<%= javascript_include_tag "application" %>
</body>
</html>

app/views/login/_form.html.erb
<%= form_for(Company.new, url: companies_login_path, html: {class: 'form-horizontal'}) do |f| %>
    <div class="control-group">
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>
    <div class="control-group">
      <%= f.label :password %><br>
      <%= f.password_field :password %>
    </div>
    <div class="control-group controls">
      <%= f.submit "Login", class: 'btn btn-primary' %>
    </div>
<% end %>

app/views/login/new.html.erb
<h1>Company Login</h1>

<%= render 'form' %>

<%= link_to "Back", root_path %>